baseurl = "https://thedatawitch.com/"
title = "The Data Witch"
author = "Nathania Johnson"
canonifyurls = true
languagecode = "en"
theme = "fillorian-theme"
Paginate = 10

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

pygmentsStyle = "bw"
pygmentsCodefences = true
pygmentsUseClassic = true

[params]
  sitename = "The Data Witch"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "GitHub"
    url  = "https://github.com/wandernat"
[[menu.main]]
    name = "Twitter"
    url  = "https://twitter.com/nlj"

